import './globals.css';

import type { Metadata } from 'next';
import Image from 'next/image';
import { Roboto } from 'next/font/google';

import { Background } from '@/constants/images';
import { Header } from '@/components/molecules';

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] });

export const metadata: Metadata = {
  title: 'Blockchain Project',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="relative flex-1 h-full">
        <div className="absolute top-0 right-0 bottom-0 left-0 h-full bg-black z-[-2]" />
        <Image
          src={Background}
          alt="blockchain background"
          width={1920}
          height={400}
          className="z-[-1] absolute top-0 left-0"
        />
        <Header />
        <main className="relative flex-1 h-full">{children}</main>
      </body>
    </html>
  );
}
